/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universitydatabasemanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import universitydatabasemanagementsystem.Connection.DataBaseConnection;

/**
 * The StudentPortal class represents the main interface for managing student records in the Bahria University Database Management System.
 * It allows users to view, modify, delete, and search for student records, as well as perform other related tasks like GPA calculation and accessing the results database.
 * This class also provides a graphical user interface (GUI) for interacting with the database.
 *
 * @author 
 * @version 
 * @since 
 */

public class StudentPortal extends javax.swing.JFrame {
	
    /**
     * Creates new form StudentPortal
     */
    public StudentPortal() {
        initComponents();
        LoadStudentRecordTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 public void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LogOut1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ModifyButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        EnrolmentField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        AgeField = new javax.swing.JTextField();
        DeptField = new javax.swing.JTextField();
        SectionField = new javax.swing.JTextField();
        PhoneNoField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        IDSearchField = new javax.swing.JTextField();
        NameSearchField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        IDSearchButton = new javax.swing.JButton();
        NameSearchButton = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentRecordTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        AddNewRecordButton = new javax.swing.JButton();
        GPACalculator = new javax.swing.JButton();
        ResultDataBase = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Portal | Bahria University Database Management System");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(910, 600));

        jPanel2.setBackground(new java.awt.Color(0, 0, 44));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STUDENT PORTAL");

        LogOut1.setBackground(new java.awt.Color(35, 133, 255));
        LogOut1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LogOut1.setForeground(new java.awt.Color(204, 204, 255));
        LogOut1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universitydatabasemanagementsystem/Images/logout.png"))); // NOI18N
        LogOut1.setText("LogOut");
        LogOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOut1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogOut1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("   Enrollment No:");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setText("  Student Name:");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("              Age:");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Department:");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setText("            Section:");

        ModifyButton.setBackground(new java.awt.Color(0, 0, 204));
        ModifyButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ModifyButton.setForeground(new java.awt.Color(255, 255, 255));
        ModifyButton.setText("Modify");
        ModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyButtonActionPerformed(evt);
            }
        });

        DeleteButton.setBackground(new java.awt.Color(204, 0, 0));
        DeleteButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("From this Panel you can edit/modify and delete existing records.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        EnrolmentField.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("        Phone No:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(93, 93, 93)
                            .addComponent(ModifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addComponent(jLabel5))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel7)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel4)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PhoneNoField)
                                .addComponent(EnrolmentField)
                                .addComponent(NameField)
                                .addComponent(AgeField)
                                .addComponent(DeptField)
                                .addComponent(SectionField)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(EnrolmentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeptField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SectionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModifyButton)
                    .addComponent(DeleteButton))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        IDSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDSearchFieldActionPerformed(evt);
            }
        });

        NameSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameSearchFieldActionPerformed(evt);
            }
        });

        jLabel2.setText(" Search by Name");

        jLabel8.setText("Search by ID :");

        IDSearchButton.setBackground(new java.awt.Color(0, 67, 98));
        IDSearchButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        IDSearchButton.setForeground(new java.awt.Color(255, 255, 255));
        IDSearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universitydatabasemanagementsystem/Images/Search icon.jpg"))); // NOI18N
        IDSearchButton.setText(" Search");
        IDSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDSearchButtonActionPerformed(evt);
            }
        });

        NameSearchButton.setBackground(new java.awt.Color(0, 67, 98));
        NameSearchButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NameSearchButton.setForeground(new java.awt.Color(255, 255, 255));
        NameSearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universitydatabasemanagementsystem/Images/Search icon.jpg"))); // NOI18N
        NameSearchButton.setText(" Search");
        NameSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameSearchButtonActionPerformed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(255, 51, 51));
        Exit.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universitydatabasemanagementsystem/Images/Exit.png"))); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(153, 255, 51));
        Back.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universitydatabasemanagementsystem/Images/back icon.png"))); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        StudentRecordTable.setBackground(new java.awt.Color(102, 102, 102));
        StudentRecordTable.setForeground(new java.awt.Color(255, 255, 255));
        StudentRecordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enrolment No", "Name", "Age", "Department", "Section", "Phone No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StudentRecordTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentRecordTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(StudentRecordTable);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("Listed Students Records");

        AddNewRecordButton.setBackground(new java.awt.Color(255, 255, 255));
        AddNewRecordButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddNewRecordButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universitydatabasemanagementsystem/Images/Add New Record Icon.jpg"))); // NOI18N
        AddNewRecordButton.setText("Add New Record");
        AddNewRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewRecordButtonActionPerformed(evt);
            }
        });

        GPACalculator.setBackground(new java.awt.Color(255, 255, 255));
        GPACalculator.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GPACalculator.setText("GPA Calculator");
        GPACalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPACalculatorActionPerformed(evt);
            }
        });

        ResultDataBase.setBackground(new java.awt.Color(255, 255, 255));
        ResultDataBase.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ResultDataBase.setText("Results DataBase");
        ResultDataBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultDataBaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                            .addComponent(IDSearchField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NameSearchField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(IDSearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(NameSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(GPACalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddNewRecordButton)
                                    .addComponent(ResultDataBase, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Exit)
                        .addGap(19, 19, 19))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(IDSearchButton)
                                        .addGap(26, 26, 26)
                                        .addComponent(NameSearchButton))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(IDSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NameSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(GPACalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ResultDataBase, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AddNewRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(Exit))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(940, 635));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Loads student records from the database into the StudentRecordTable.
     * This method populates the table with student enrollment information, including name, age, department, section, and phone number.
     */
    public void LoadStudentRecordTable(){
        
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        
        try{
            Class.forName(DataBaseConnection.DriverPath);
            con = DriverManager.getConnection(DataBaseConnection.DatabaseFile);
            String query = "select * from Student";
            ps = con.prepareStatement(query);
            rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel)StudentRecordTable.getModel();
            while(rs.next()){
                Object[] row = new Object[6];
                row[0] = rs.getInt("Enrollment");
                row[1] = rs.getString("Name");
                row[2] = rs.getString("Age");
                row[3] = rs.getString("Department");
                row[4] = rs.getString("Section");
                row[5] = rs.getString("Phone");
                model.addRow(row); 
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * Action performed when the "Modify" button is clicked.
     * This method updates a student's record in the database based on the provided information.
     * It modifies the name, age, department, section, and phone number of the selected student.
     */
    private void ModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyButtonActionPerformed
        // TODO add your handling code here:       
        String enrollment = EnrolmentField.getText();
        String name       = NameField.getText();
        String age        = AgeField.getText();
        String dept       = DeptField.getText();
        String section    = SectionField.getText();
        String phoneNo    = PhoneNoField.getText();

        if(!EnrolmentField.getText().equals(""))
        {
            Connection con = null;
            PreparedStatement ps = null, psResult = null;
            ResultSet rs = null ;
            
            try{
                Class.forName(DataBaseConnection.DriverPath);
                con = DriverManager.getConnection(DataBaseConnection.DatabaseFile);
                
                String query = "Update Student set Name = ? , Age = ? , Department = ? , Section = ? , Phone = ? where Enrollment = ? ";
                ps = con.prepareStatement(query);
                
                ps.setString(6, enrollment);
                ps.setString(1, name);
                ps.setString(2, age);
                ps.setString(3, dept);
                ps.setString(4, section);
                ps.setString(5, phoneNo);
                
                int result = ps.executeUpdate();
                
                if(result > 0)
                {
                    JOptionPane.showMessageDialog(null, "Student Records Modifed Sucessfully.");
                    DefaultTableModel model = (DefaultTableModel)StudentRecordTable.getModel();
                    model.setRowCount(0);
                    
                    EnrolmentField.setText("");
                    NameField.setText("");
                    AgeField.setText("");
                    DeptField.setText("");
                    SectionField.setText("");
                    PhoneNoField.setText("");
                    
                    LoadStudentRecordTable();
                    
                    String query1 = "Update Results set Name = ? where Enrollment = ? ";
                    psResult = con.prepareStatement(query1);

                    psResult.setString(2, enrollment);
                    psResult.setString(1, name);
                    psResult.executeUpdate();

                }
                else{
                    JOptionPane.showMessageDialog(null, "Student Records Not Modifed.");
                }
            }
            catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Student Record Must be Selected First From the Table.");
        }
  
    }//GEN-LAST:event_ModifyButtonActionPerformed

    /**
     * Action performed when the "Delete" button is clicked.
     * This method deletes a student's record from the database based on the enrollment number.
     * It removes the selected student's information from both the student and results databases.
     */
    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        String enrollment = EnrolmentField.getText();
        
        if(!EnrolmentField.getText().equals(""))
        {
            Connection con = null;
            PreparedStatement ps = null, psResult = null;
            ResultSet rs = null ;
            
            try{
                Class.forName(DataBaseConnection.DriverPath);
                con = DriverManager.getConnection(DataBaseConnection.DatabaseFile);
                
                String query  = "Delete from Student where Enrollment = ?";
                ps = con.prepareStatement(query);
                
                ps.setString(1, enrollment);
                int result = ps.executeUpdate();
                
                if(result > 0)
                {
                    JOptionPane.showMessageDialog(null, "Student Records Deleted Sucessfully");
                    DefaultTableModel model = (DefaultTableModel)StudentRecordTable.getModel();
                    model.setRowCount(0);
                    
                    EnrolmentField.setText("");
                    NameField.setText("");
                    AgeField.setText("");
                    DeptField.setText("");
                    SectionField.setText("");
                    PhoneNoField.setText("");
                    
                    LoadStudentRecordTable();
                    
                    String query1  = "Delete from Results where Enrollment = ?";
                    psResult = con.prepareStatement(query1);
                    psResult.setString(1, enrollment);
                    psResult.executeUpdate();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Student Records Not Deleted.");
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }           
        }else{
             JOptionPane.showMessageDialog(null, "Student Records Must Be Selected First From Table.");
        }
        
    }//GEN-LAST:event_DeleteButtonActionPerformed

    /**
     * Action performed when the ID search button is clicked.
     * This method allows users to search for a student by enrollment number and display the matching records in the table.
     */
    private void IDSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDSearchFieldActionPerformed
    
    /**
     * Action performed when the Name search button is clicked.
     * This method allows users to search for a student by name and display the matching records in the table.
     */
    private void NameSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameSearchFieldActionPerformed


    private void IDSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDSearchButtonActionPerformed
        // TODO add your handling code here:
        if(!IDSearchField.getText().equals("")){
            Connection con = null;
            PreparedStatement ps = null;
            ResultSet rs = null;
            try{
                Class.forName(DataBaseConnection.DriverPath);
                con = DriverManager.getConnection(DataBaseConnection.DatabaseFile);
                
                String query = "select * from Student where Enrollment = ?";
                ps = con.prepareStatement(query);
                String enroll = IDSearchField.getText();
                ps.setString(1,enroll);
                rs = ps.executeQuery();
                
                DefaultTableModel model = (DefaultTableModel)StudentRecordTable.getModel();
                model.setRowCount(0);
                
                while(rs.next()){
                    Object[] row = new Object[6];
                    row[0] = rs.getInt("Enrollment");
                    row[1] = rs.getString("Name");
                    row[2] = rs.getString("Age");
                    row[3] = rs.getString("Department");
                    row[4] = rs.getString("Section");
                    row[5] = rs.getString("Phone");
                    model.addRow(row);
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else{
            DefaultTableModel model = (DefaultTableModel)StudentRecordTable.getModel();
            model.setRowCount(0);
            LoadStudentRecordTable();
        }
    }//GEN-LAST:event_IDSearchButtonActionPerformed
    
    
    private void NameSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameSearchButtonActionPerformed
        // TODO add your handling code here:
        if(!NameSearchField.getText().equals("")){
            Connection con = null;
            PreparedStatement ps = null;
            ResultSet rs = null;
            
            try{
                Class.forName(DataBaseConnection.DriverPath);
                con = DriverManager.getConnection(DataBaseConnection.DatabaseFile);
                String query = "select * from Student where Name = ?";
                
                ps = con.prepareStatement(query);
                String Name = NameSearchField.getText();
                ps.setString(1,Name);
                rs = ps.executeQuery();
                
                DefaultTableModel model = (DefaultTableModel)StudentRecordTable.getModel();
                model.setRowCount(0);
                
                while(rs.next()){
                    Object[] row = new Object[6];
                    row[0] = rs.getInt("Enrollment");
                    row[1] = rs.getString("Name");
                    row[2] = rs.getString("Age");
                    row[3] = rs.getString("Department");
                    row[4] = rs.getString("Section");
                    row[5] = rs.getString("Phone");
                    model.addRow(row);
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else{
            DefaultTableModel model = (DefaultTableModel)StudentRecordTable.getModel();
            model.setRowCount(0);
            LoadStudentRecordTable();
        }

    }//GEN-LAST:event_NameSearchButtonActionPerformed

    /**
     * Action performed when the "Exit" button is clicked.
     * This method exits the application.
     */
    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * Action performed when the "Back" button is clicked.
     * This method navigates back to the main page of the application.
     */
    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        MainPage main = new MainPage();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * Action performed when a row in the StudentRecordTable is clicked.
     * This method retrieves the selected student's information and populates the input fields for modification or deletion.
     */
    private void StudentRecordTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentRecordTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)StudentRecordTable.getModel();
        int selectedRowIndex = StudentRecordTable.getSelectedRow();
        EnrolmentField.setText(model.getValueAt(selectedRowIndex, 0).toString());
        NameField.setText(model.getValueAt(selectedRowIndex, 1).toString());
        AgeField.setText(model.getValueAt(selectedRowIndex, 2).toString());
        DeptField.setText(model.getValueAt(selectedRowIndex, 3).toString());
        SectionField.setText(model.getValueAt(selectedRowIndex, 4).toString());
        PhoneNoField.setText(model.getValueAt(selectedRowIndex, 5).toString());
    }//GEN-LAST:event_StudentRecordTableMouseClicked

    /**
     * Action performed when the "Add New Record" button is clicked.
     * This method opens a new window for adding a new student record to the database.
     */
    private void AddNewRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewRecordButtonActionPerformed
        // TODO add your handling code here:
        AddNewStudent addS = new AddNewStudent();
        addS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AddNewRecordButtonActionPerformed

    /**
     * Action performed when the "Log Out" button is clicked.
     * This method logs the user out and returns to the welcome page.
     */
    private void LogOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOut1ActionPerformed
        // TODO add your handling code here:
        WelcomePage main = new WelcomePage();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LogOut1ActionPerformed

    /**
     * Action performed when the "GPA Calculator" button is clicked.
     * This method clears the GPA calculator database and opens the GPA calculation interface.
     */
    private void GPACalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPACalculatorActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        PreparedStatement ps = null;
            
        try{
            Class.forName(DataBaseConnection.DriverPath);
            con = DriverManager.getConnection(DataBaseConnection.DatabaseFile);
                
            String query  = "Delete from GPACalculator";
            ps = con.prepareStatement(query);
                
            ps.executeUpdate();                       
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
        }
        
        GPACalculator gpaCal = new GPACalculator();
        gpaCal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_GPACalculatorActionPerformed

    /**
     * Action performed when the "Results Database" button is clicked.
     * This method navigates to the student results database interface.
     */
    private void ResultDataBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultDataBaseActionPerformed
        // TODO add your handling code here:
       StudentsResultDataBase rDataBase = new StudentsResultDataBase();
        rDataBase.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ResultDataBaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewRecordButton;
    private javax.swing.JTextField AgeField;
    private javax.swing.JButton Back;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTextField DeptField;
    private javax.swing.JTextField EnrolmentField;
    private javax.swing.JButton Exit;
    private javax.swing.JButton GPACalculator;
    private javax.swing.JButton IDSearchButton;
    private javax.swing.JTextField IDSearchField;
    private javax.swing.JButton LogOut1;
    private javax.swing.JButton ModifyButton;
    private javax.swing.JTextField NameField;
    private javax.swing.JButton NameSearchButton;
    private javax.swing.JTextField NameSearchField;
    private javax.swing.JTextField PhoneNoField;
    private javax.swing.JButton ResultDataBase;
    private javax.swing.JTextField SectionField;
    private javax.swing.JTable StudentRecordTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
